name: "Hello world workflow"
# Controls when the actions will run. Triggers the workflow on push on the master or procuction branch


on: 
  push:
    branches:
      - master  
      - production

jobs:
  hello_world:
    runs-on: ubuntu latest
    steps:
      - name: Checkout code
      - run: echo "Hello world"
